### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/crafter#1]
- [ ] finish TCP layer
- [ ] finish ICMP layer
- [ ] add other layers
- [ ] add ability to get a packet by packet number
- [x] add ability to get packet payload by packet number
- [ ] add ability to decode packet data (harder than it should be - this is partially complete)

**Comment by synikitin** [comment]
Any chance of getting UDP support?
